# Generated by Django 4.1.7 on 2023-02-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_menuitem_parent_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="menu_id",
            new_name="menu",
        ),
    ]
