# Generated by Django 4.1.7 on 2023-02-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_rename_menu_id_menuitem_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="slug",
        ),
    ]
