# Generated by Django 4.1.7 on 2023-02-21 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_remove_menuitem_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="task.menuitem",
            ),
        ),
    ]
